// ********RoostGPT********
// Test generated by RoostGPT for test vertex-32k-chat-unit using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
package Validator_test

import (
	"testing"
	"learning-go/beginner-programs/Email-Validator/Validator"
)

func TestIsValidEmailPositive(t *testing.T) {
	testEmails := []string{
		"example@test.com",
		"user+mailbox/department=shipping@example.com",
		"customer/department=shipping@example.com",
		"$A12345@example.com",
		"!def!xyz%abc@example.com",
		"_Yosemite.Sam@example.com",
		"~@example.com",
	}

	for _, email := range testEmails {
		if !Validator.IsValidEmail(email) {
			t.Errorf("IsValidEmail(%s) = false, want true", email)
		}
	}
}

func TestIsValidEmailNegative(t *testing.T) {
	invalidEmails := []string{
		"example..test@example.com",
		".test@example.com",
		"test@.example.com",
		"test@example..com",
		"test@example_com",
		"@example.com",
		"test@",
		"test@example.",
		"",
		"     ",
	}

	for _, email := range invalidEmails {
		if Validator.IsValidEmail(email) {
			t.Errorf("IsValidEmail(%s) = true, want false", email)
		}
	}
}

