// Test generated by RoostGPT for test TannerGabriel-learning-go using AI Type Open AI and AI Model gpt-4

package Validator

import (
	"testing"
)

func TestIsValidEmail_d2603fb18f(t *testing.T) {
	// Test case for valid email
	email := "test@example.com"
	if !IsValidEmail(email) {
		t.Error("Expected true, got ", IsValidEmail(email))
	}

	// Test case for invalid email
	email = "test@.com"
	if IsValidEmail(email) {
		t.Error("Expected false, got ", IsValidEmail(email))
	}

	// Test case for email with length more than 254
	email = "a"
	for i := 0; i < 260; i++ {
		email += "a"
	}
	email += "@example.com"
	if IsValidEmail(email) {
		t.Error("Expected false, got ", IsValidEmail(email))
	}

	// Test case for empty email
	email = ""
	if IsValidEmail(email) {
		t.Error("Expected false, got ", IsValidEmail(email))
	}
}
